---
# Variable configuration.
- ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- ansible.builtin.include_tasks: setup-RockyLinux.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure PaSSHPort
- ansible.builtin.include_tasks: users.yml
- ansible.builtin.include_tasks: configure.yml
- ansible.builtin.include_tasks: hosts.yml

