---
- name: Add the Epel Repo
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install the PaSSHPort
  ansible.builtin.dnf:
    name:
      - python3-pip
      - git 
      - openssl 
      - python3-devel 
      - gcc 
      - ibffi-devel
    state: latest

- name: Update pip
  ansible.builtin.pip:
    name: pip
    state: present

- name: Install python module for PaSSHPort
  ansible.bulitin.pip:
    name:
      - virtualenv
      - pathlib2
    state: present

- name: Add passport users
  ansible.builtin.user:
    name: passport
    shell: /bin/bash
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 4098
    ssh_key_file: .ssh/id_rsa
  