---
- name: Add the Epel Repo
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install the PaSSHPort
  ansible.builtin.dnf:
    name:
      - python3-pip
      - git 
      - openssl 
      - python3-devel 
      - gcc 
      - ibffi-devel
    state: latest

- name: Update pip
  ansible.builtin.pip:
    name: pip


      