---
- name: Add the Epel Repo
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install the PaSSHPort
  ansible.builtin.dnf:
    name:
      - python3-pip
      - git 
      - openssl 
      - python3-devel 
      - gcc 
      - ibffi-devel
    state: latest

- name: Update pip
  ansible.builtin.pip:
    name: pip
    state: present

- name: Install python module for PaSSHPort
  ansible.bulitin.pip:
    name:
      - virtualenv
      - pathlib2
    state: present

- name: Add passhport users
  ansible.builtin.user:
    name: passhport
    shell: /bin/bash
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 4098
    ssh_key_file: .ssh/id_rsa
  
- name: Ensure the virtual environment exists
  ansible.builtin.pip:
    virtualenv: "{{ passhport_venv_dir }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: passhport

- name: Get PaSSHPort source from git
  ansible.builtin.git:
    repo: http://github.com/LibrIT/passhport.git
    clone: yes
    dest: /home/passhport/
  become_user: passhport

- name: Install PaSSHPort pip requirements
  ansible.builtin.pip:
    virtualenv: "{{ passhport_venv_dir }}"
    requirements: /home/passhport/passhport/requirements.txt
  become_user: passhport

- name: Create Logs folder 
  ansible.builtin.file:
    path: /var/log/passhport/
    state: directory
    owner: passhport
    group: passhport

- name: Create etc folder 
  ansible.builtin.file:
    path: /etc/passhport/
    state: directory

- name: Copy PaSSHPort config to etc
  ansible.builtin.copy:
    src: /home/passhport/passhport/passhport/passhport.ini
    dest: /etc/passhport/
    remote_src: true

- name: Copy PaSSHPort config to etc
  ansible.builtin.copy:
    src: /home/passhport/passhport/passhportd/passhportd.ini
    dest: /etc/passhport/
    remote_src: true

- name: Copy PaSSHPort config to etc
  ansible.builtin.copy:
    src: /home/passhport/passhport/passhport-admin/passhport-admin.ini
    dest: /etc/passhport/
    remote_src: true

- name: Modify the Listening IP
  ansible.builtin.lineinfile:
    path: /etc/passhport/passportd.ini
    regexp: ^LISTENING_IP
    line: LISTENING_IP = {{ passhport_listen_ip }}

- name: Modify the Listening Port
  ansible.builtin.lineinfile:
    path: /etc/passhport/passportd.ini
    regexp: ^PORT
    line: PORT = {{ passhport_listen_port }}